### ISSUE TITLE
sa11y sometimes flags issues that it creates

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov_sa11y#20]
On this page, there are no duplicate IDs - but sometimes sa11y creates its own IDs and flags an issue with them:

![image](https://user-images.githubusercontent.com/19519457/235201535-052021e2-d303-4b8e-8017-b3be6536370f.png)

**Comment by keelanfh** [comment]
Example of the code that sa11y injects:

```html
<span id="sa11y-h9" class="sa11y-heading-label">H3</span>
<span id="sa11y-h9" class="sa11y-heading-label sa11y-error-border sa11y-label-visible">H3</span>
```

**Comment by keelanfh** [comment]
Looking more closely, it looks like two separate instances of sa11y are running at the same time and conflicting.

**Comment by markconroy** [comment]
@keelanfh is this still an issue for you? I can't see to replicate it.

**Comment by keelanfh** [comment]
I can't replicate this today. There might have been some changes to sa11y since then? I'll close for now and re-raise if it comes up again
