### ISSUE TITLE
Update to Sa11y 3.2.2

### ISSUE THREAD

**Issue by AWearring** [localgovdrupal/localgov_sa11y#33]
In `localgov_sa11y.libraries.yml` can we update this to use 3.2.2

So change to this:
```
sa11y-files:
  js:
    https://cdn.jsdelivr.net/combine/gh/ryersondmp/sa11y@3.2.2/dist/js/lang/en.umd.js,gh/ryersondmp/sa11y@3.2.2/dist/js/sa11y.umd.min.js: { type: external, minified: true}
  css:
    theme:
      https://cdn.jsdelivr.net/gh/ryersondmp/sa11y@3.2.2/dist/css/sa11y.min.css: { type: external, minified: true}
 ```

And put out a release (1.0.0-beta6)

**Comment by markconroy** [comment]
This looks fine @AWearring 

Is there anything in particular that we need from that latest version, or is this just keeping us up to date?

**Comment by AWearring** [comment]
Just keeping it up to date. 
However, the latest release of the module beta 5 is on 3.0.0, so we could do with a new release.

**Comment by markconroy** [comment]
Here's a new release now - https://github.com/localgovdrupal/localgov_sa11y/releases/tag/1.0.0-beta6
