### ISSUE TITLE
Contrast does not seem to be working in localgov_microsites

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_sa11y#40]
While testing and demonstrating LocalGov Microsites at Drupalcon and Drupal London, I tried to get localgov_sa11y to trigger accessibility warnings for bad colour choices for header and fonts, but it does not seem to trigger contrast warnings.

I'm sure it used to.

Any ideas?

![image](https://github.com/user-attachments/assets/5d0ea68b-3018-4764-aef6-638862fd79c0)

**Comment by markconroy** [comment]
Jeez, this took a bit of time to track down, but looks like it's fixed in 3.2.3 

> Bug fix: Fixed a serious bug where contrast checking would stop flagging issues once it comes across a visually hidden element (for example, an .sr-only class).

So, if we have a .visually-hidden class somewhere, Sa11y was stopping doing its business.

PR on the way.
