### ISSUE TITLE
Suggestion: Only have content that Content Editors have access to change being highlighted by the Sa11y App

### ISSUE THREAD

**Issue by AWearring** [localgovdrupal/localgov_sa11y#43]
## Suggestion
Only have content that Content Editors have access to change to be highlighted by the Sa11y App

### Reasoning
If content editors can't influence/change the content being highlighted do we actually want it to be highlighted, some content editors may ignore the warnings/errors if they get the impression they can't do anything about them.

### Method
Create a configuration form and use the settings to add/update variables in `localgov-sa11y.js`

Form to have the following options:
- checkRoot: "String. Input a single selector to scan a specific region of the page. This selector should exist on every page of your website. For example, pass `main` for the main content area."
Default: `div.dialog-off-canvas-main-canvas`
- containerIgnore: "String. Ignore specific regions of the page"
Default: [empty]
- contrastIgnore: "String. Ignore specific elements from the contrast check"
Default: [empty]

Maybe consider adding the following options too:
- exportResultsPlugin: "Boolean. Set to `true` if you would like to add buttons that allow users to export issues as CSV or HTML"
Default: `false`
- checkAllHideToggles: "Boolean. Set to `true` if you would like to visually hide all toggle switches in the Settings panel. This will not hide the Dark Mode or Colour Filter toggles" (on testing it appears to also not hide the Readability toggle - AW)
Default: `false`
- panelPosition: "String. Move position of panel in any four corners. Choose from top-left, top-right, left, and right"
Default: `right`

### Additional suggestion
Restrict the changes to `localgov-sa11y.js` so that they only are in effect if the user doesn't have certain roles (e.g. not admin)

**Comment by AWearring** [comment]
@markconroy 
I've realised that I made a mistake naming the configuration form - referencing it as `localgov_sa11y_options.settings` instead of `localgov_sa11y.settings` - I'll update the code

This is the error I get when running `drush cim` after saving the config form and a `drush cex`:

```
[error]  Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.
Configuration <em class="placeholder">localgov_sa11y_options.settings</em> depends on the <em class="placeholder">localgov_sa11y_options</em> extension that will not be installed after import. in Drupal\Core\Config\ConfigImporter->validate() (line 823 of D:\NorthKesteven\web\core\lib\Drupal\Core\Config\ConfigImporter.php).
```

**Comment by markconroy** [comment]
@AWearring let's close this issue now, I think the latest release fixes it.
