### ISSUE TITLE
Should we turn on contrast/readability/etc by default?

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_sa11y#9]

**Comment by AWearring** [comment]
If we set `checkAllHideToggles` to true this turns them all on and hides the toggles - or have it as part of a config form, see my suggestion for this: https://github.com/localgovdrupal/localgov_sa11y/issues/43

**Comment by markconroy** [comment]
Turning that on, as you say, hides all the toggles. I don't want us to do that.


![Screenshot 2024-10-25 at 12 28 50](https://github.com/user-attachments/assets/1a3b0b94-f835-47e2-b6f1-4fe5a8e9a1d6)

I think it's good that people have the option to turn them back on/off if they wish. 

I have no problem with us turning things on by default, but let's also leave the mechanism to turn them back off.

**Comment by markconroy** [comment]
@AWearring will we close this issue? I think it's superceded by the settings form issue/PR that you have created.
